module com.arvatosystems.t9t.core.jpa {
	exports com.arvatosystems.t9t.core.jpa.persistence.impl;
	exports com.arvatosystems.t9t.batch.jpa.persistence;
	exports com.arvatosystems.t9t.bucket.jpa.request;
	exports com.arvatosystems.t9t.event.jpa.persistence.impl;
	exports com.arvatosystems.t9t.plugins.jpa.impl;
	exports com.arvatosystems.t9t.statistics.service.impl;
	exports com.arvatosystems.t9t.core.jpa.entities;
	exports com.arvatosystems.t9t.batch.jpa.mapping.impl;
	exports com.arvatosystems.t9t.core.jpa.mapping.impl;
	exports com.arvatosystems.t9t.batch.jpa.persistence.impl;
	exports com.arvatosystems.t9t.event.jpa.mapping.impl;
	exports com.arvatosystems.t9t.bucket.jpa.impl;
	exports com.arvatosystems.t9t.event.jpa.entities;
	exports com.arvatosystems.t9t.batch.jpa.request;
	exports com.arvatosystems.t9t.plugins.jpa.request;
	exports com.arvatosystems.t9t.bucket.jpa.mapping;
	exports com.arvatosystems.t9t.event.jpa.mapping;
	exports com.arvatosystems.t9t.batch.jpa.entities;
	exports com.arvatosystems.t9t.event.jpa.impl;
	exports com.arvatosystems.t9t.bucket.jpa.mapping.impl;
	exports com.arvatosystems.t9t.core.jpa.mapping;
	exports com.arvatosystems.t9t.bucket.jpa.persistence;
	exports com.arvatosystems.t9t.plugins.jpa.mapping.impl;
	exports com.arvatosystems.t9t.plugins.jpa.persistence.impl;
	exports com.arvatosystems.t9t.bucket.jpa.persistence.impl;
	exports com.arvatosystems.t9t.plugins.jpa.entities;
	exports com.arvatosystems.t9t.core.jpa.impl;
	exports com.arvatosystems.t9t.event.jpa.request;
	exports com.arvatosystems.t9t.event.jpa.persistence;
	exports com.arvatosystems.t9t.batch.jpa.impl;
	exports com.arvatosystems.t9t.plugins.jpa.mapping;
	exports com.arvatosystems.t9t.plugins.jpa.persistence;
	exports com.arvatosystems.t9t.core.jpa.request;
	exports com.arvatosystems.t9t.batch.jpa.mapping;
	exports com.arvatosystems.t9t.bucket.jpa.entities;
	exports com.arvatosystems.t9t.core.jpa.persistence;

	requires transitive com.arvatosystems.t9t.annotations.jpa;
	requires transitive com.arvatosystems.t9t.base.api;
	requires transitive com.arvatosystems.t9t.base.jpa;
	requires transitive com.arvatosystems.t9t.base.sapi;
	requires transitive com.arvatosystems.t9t.core.api;
	requires transitive com.arvatosystems.t9t.core.sapi;
	requires transitive com.arvatosystems.t9t.server;
	requires transitive com.arvatosystems.t9t.cfg;  // FIXME: remove this, only needed in a single place, replace by lookup method
	requires transitive com.google.common;
	requires transitive de.jpaw.annotations;
	requires transitive de.jpaw.bonaparte.api;
	requires transitive de.jpaw.bonaparte.core;
	requires transitive de.jpaw.bonaparte.refs;
	requires transitive de.jpaw.jdp;
	requires transitive de.jpaw.jpaw.enums;
	requires transitive de.jpaw.jpaw.util;
	requires transitive de.jpaw.persistence.core;
	requires transitive de.jpaw.persistence.refs;
	requires transitive java.validation;
	requires transitive java.persistence;
	requires transitive org.eclipse.xtext.xbase.lib;
	requires transitive org.joda.time;
	requires org.slf4j;
}