CREATE SEQUENCE p28_cfg_ai_dto_assist_s;

CREATE TABLE p28_cfg_ai_dto_assist (
    -- table columns of java class TrackingBase
    -- table columns of java class WriteTracking
      c_app_user_id varchar(16) NOT NULL
    , c_timestamp timestamp(0) DEFAULT CURRENT_TIMESTAMP NOT NULL
    , c_process_ref bigint NOT NULL
    -- table columns of java class FullTracking
    , m_app_user_id varchar(16) NOT NULL
    , m_timestamp timestamp(0) DEFAULT CURRENT_TIMESTAMP NOT NULL
    , m_process_ref bigint NOT NULL
    -- table columns of java class FullTrackingWithVersion
    , version integer NOT NULL
    -- table columns of java class InternalTenantId
    , tenant_id varchar(16) NOT NULL
    -- table columns of java class AbstractRef
    -- table columns of java class Ref
    , object_ref bigint NOT NULL
    -- table columns of java class AiDtoAssistRef
    -- table columns of java class AiDtoAssistDTO
    , pqon varchar(36) NOT NULL
    , description varchar(80) NOT NULL
    , ai_assistant_ref bigint NOT NULL
    , role varchar(65536) NOT NULL
    , dto_instructions varchar(65536) NOT NULL
    , dto_schema varchar(65536)
    , z text
);

ALTER TABLE p28_cfg_ai_dto_assist ADD CONSTRAINT p28_cfg_ai_dto_assist_pk PRIMARY KEY (
    object_ref
);
CREATE UNIQUE INDEX p28_cfg_ai_dto_assist_u1 ON p28_cfg_ai_dto_assist (
    tenant_id, pqon
);

-- comments for columns of java class TrackingBase
-- comments for columns of java class WriteTracking
COMMENT ON COLUMN p28_cfg_ai_dto_assist.c_timestamp IS 'noinsert removed, causes problems with H2 unit tests';
-- comments for columns of java class FullTracking
-- comments for columns of java class FullTrackingWithVersion
-- comments for columns of java class InternalTenantId
COMMENT ON COLUMN p28_cfg_ai_dto_assist.tenant_id IS 'the multitenancy discriminator';
-- comments for columns of java class AbstractRef
-- comments for columns of java class Ref
COMMENT ON COLUMN p28_cfg_ai_dto_assist.object_ref IS 'objectRef, as a primary key it cannot be changed and, if persisted, is never null';
-- comments for columns of java class AiDtoAssistRef
-- comments for columns of java class AiDtoAssistDTO
COMMENT ON COLUMN p28_cfg_ai_dto_assist.pqon IS 'PQON of the DTO to be created / edited';
COMMENT ON COLUMN p28_cfg_ai_dto_assist.description IS 'description / notes';
COMMENT ON COLUMN p28_cfg_ai_dto_assist.ai_assistant_ref IS 'which LLM to use / LLM parameters';
COMMENT ON COLUMN p28_cfg_ai_dto_assist.role IS 'role input for the LLM';
COMMENT ON COLUMN p28_cfg_ai_dto_assist.dto_instructions IS 'DTO specific instructions, will be pasted into the prompt';
COMMENT ON COLUMN p28_cfg_ai_dto_assist.dto_schema IS 'JSON schema for the DTO. If missing, it will be autogenerated';
COMMENT ON COLUMN p28_cfg_ai_dto_assist.z IS 'project specific extensions';

CREATE OR REPLACE VIEW p28_cfg_ai_dto_assist_nt AS SELECT
    -- columns of java class InternalTenantId
    t0.tenant_id AS tenant_id
    -- columns of java class AbstractRef
    -- columns of java class Ref
    , t0.object_ref AS object_ref
    -- columns of java class AiDtoAssistRef
    -- columns of java class AiDtoAssistDTO
    , t0.pqon AS pqon
    , t0.description AS description
    , t0.ai_assistant_ref AS ai_assistant_ref
    , t0.role AS role
    , t0.dto_instructions AS dto_instructions
    , t0.dto_schema AS dto_schema
    , t0.z AS z
FROM p28_cfg_ai_dto_assist t0;

CREATE OR REPLACE VIEW p28_cfg_ai_dto_assist_v AS SELECT
    -- columns of java class TrackingBase
    -- columns of java class WriteTracking
    t0.c_app_user_id AS c_app_user_id
    , t0.c_timestamp AS c_timestamp
    , t0.c_process_ref AS c_process_ref
    -- columns of java class FullTracking
    , t0.m_app_user_id AS m_app_user_id
    , t0.m_timestamp AS m_timestamp
    , t0.m_process_ref AS m_process_ref
    -- columns of java class FullTrackingWithVersion
    , t0.version AS version
    -- columns of java class InternalTenantId
    , t0.tenant_id AS tenant_id
    -- columns of java class AbstractRef
    -- columns of java class Ref
    , t0.object_ref AS object_ref
    -- columns of java class AiDtoAssistRef
    -- columns of java class AiDtoAssistDTO
    , t0.pqon AS pqon
    , t0.description AS description
    , t0.ai_assistant_ref AS ai_assistant_ref
    , t0.role AS role
    , t0.dto_instructions AS dto_instructions
    , t0.dto_schema AS dto_schema
    , t0.z AS z
FROM p28_cfg_ai_dto_assist t0;
