--
-- Copyright (c) 2012 - 2018 Arvato Systems GmbH
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

-- set NOCACHE, as caching is done by the application
CREATE SEQUENCE cm_idgen_0000_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0001_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0002_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0003_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0004_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0005_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0006_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0007_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0008_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0009_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0010_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0011_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0012_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0013_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0014_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0015_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0016_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0017_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0018_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0019_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0020_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0021_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0022_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0023_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0024_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0025_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0026_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0027_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0028_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0029_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0030_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0031_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0032_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0033_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0034_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0035_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0036_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0037_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0038_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0039_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0040_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0041_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0042_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0043_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0044_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0045_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0046_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0047_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0048_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0049_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0050_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0051_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0052_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0053_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0054_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0055_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0056_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0057_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0058_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0059_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0060_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0061_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0062_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0063_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0064_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0065_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0066_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0067_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0068_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0069_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0070_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0071_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0072_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0073_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0074_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0075_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0076_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0077_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0078_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0079_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0080_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0081_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0082_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0083_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0084_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0085_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0086_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0087_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0088_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0089_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0090_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0091_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0092_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0093_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0094_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0095_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0096_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0097_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0098_seq NOCACHE;
CREATE SEQUENCE cm_idgen_0099_seq NOCACHE;
-- unscaled sequences for use in fortytwo
CREATE SEQUENCE cm_idgen_5000_seq NOCACHE;
CREATE SEQUENCE cm_idgen_5001_seq NOCACHE;
CREATE SEQUENCE cm_idgen_5002_seq NOCACHE;
CREATE SEQUENCE cm_idgen_5003_seq NOCACHE;
CREATE SEQUENCE cm_idgen_5004_seq NOCACHE;
CREATE SEQUENCE cm_idgen_5005_seq NOCACHE;
CREATE SEQUENCE cm_idgen_5006_seq NOCACHE;
CREATE SEQUENCE cm_idgen_5007_seq NOCACHE;
CREATE SEQUENCE cm_idgen_5008_seq NOCACHE;
CREATE SEQUENCE cm_idgen_5009_seq NOCACHE;
-- unscaled sequences for use in main applications
CREATE SEQUENCE cm_idgen_6000_seq NOCACHE;
CREATE SEQUENCE cm_idgen_6001_seq NOCACHE;
CREATE SEQUENCE cm_idgen_6002_seq NOCACHE;
CREATE SEQUENCE cm_idgen_6003_seq NOCACHE;
CREATE SEQUENCE cm_idgen_6004_seq NOCACHE;
CREATE SEQUENCE cm_idgen_6005_seq NOCACHE;
CREATE SEQUENCE cm_idgen_6006_seq NOCACHE;
CREATE SEQUENCE cm_idgen_6007_seq NOCACHE;
CREATE SEQUENCE cm_idgen_6008_seq NOCACHE;
CREATE SEQUENCE cm_idgen_6009_seq NOCACHE;
-- unscaled sequences for use in customizations
CREATE SEQUENCE cm_idgen_7000_seq NOCACHE;
CREATE SEQUENCE cm_idgen_7001_seq NOCACHE;
CREATE SEQUENCE cm_idgen_7002_seq NOCACHE;
CREATE SEQUENCE cm_idgen_7003_seq NOCACHE;
CREATE SEQUENCE cm_idgen_7004_seq NOCACHE;
CREATE SEQUENCE cm_idgen_7005_seq NOCACHE;
CREATE SEQUENCE cm_idgen_7006_seq NOCACHE;
CREATE SEQUENCE cm_idgen_7007_seq NOCACHE;
CREATE SEQUENCE cm_idgen_7008_seq NOCACHE;
CREATE SEQUENCE cm_idgen_7009_seq NOCACHE;
