lowercaseOutputName: true
lowercaseOutputLabelNames: true
rules:
    - pattern: "org.eclipse.jetty.deploy<(.*)><>(.*)"
      name: "jetty_deploy_$2"
      labels:
        labelList: "$1"
    - pattern: "org.eclipse.jetty.deploy.providers<type=(\\w+), id=(\\d+)><>(\\w+)"
      name: "jetty_deploy_providers_$3"
      labels:
        id: "$2"
        type: "$1"
    - pattern: "org.eclipse.jetty.io<context=(.*), type=(.*), id=(\\d+)><>(\\w+)"
      name: "jetty_io_$4"
      labels:
        id: "$3"
        type: "$2"
        context: "$1"
    - pattern: "org.eclipse.jetty.io<type=(.*), id=(\\d+)><>(\\w+)"
      name: "jetty_io_$3"
      labels:
        id: "$2"
        type: "$1"
    - pattern: "org.eclipse.jetty.jmx<type=(\\w+), id=(\\d+)><>(\\w+)"
      name: "jetty_jmx_$3"
      labels:
        id: "$2"
        type: "$1"
    - pattern: "org.eclipse.jetty.logging<type=(\\w+), id=(\\d+)><>(\\w+)"
      name: "jetty_logging_$3"
      labels:
        id: "$2"
        type: "$1"
    - pattern: "org.eclipse.jetty.server<type=(\\w+), id=(\\d+)><>(\\w+)"
      name: "jetty_server_$3"
      labels:
        id: "$2"
        type: "$1"
    - pattern: "org.eclipse.jetty.server<context=(.*), type=(.*), id=(\\d+)><>(\\w+)"
      name: "jetty_server_$4"
      labels:
        id: "$3"
        type: "$2"
        context: "$1"
    - pattern: "org.eclipse.jetty.server.handler<type=(\\w+), id=(\\d+)><>(\\w+)"
      name: "jetty_server_handler_$3"
      labels:
        id: "$2"
        type: "$1"
    - pattern: "org.eclipse.jetty.server.session<type=(.*), id=(\\d+)><>(\\w+)"
      name: "jetty_server_session_$3"
      labels:
        id: "$2"
        type: "$1"
    - pattern: "org.eclipse.jetty.server.session<context=(.*), type=(.*), id=(\\d+)><>(\\w+)"
      name: "jetty_server_session_$4"
      labels:
        id: "$3"
        type: "$2"
        context: "$1"
    - pattern: "org.eclipse.jetty.util<type=(\\w+), id=(\\d+)><>(\\w+)"
      name: "jetty_util_$3"
      labels:
        id: "$2"
        type: "$1"
    - pattern: "org.eclipse.jetty.util.component<type=(\\w+), id=(\\d+)><>(\\w+)"
      name: "jetty_util_component_$3"
      labels:
        id: "$2"
        type: "$1"
    - pattern: "org.eclipse.jetty.servlet<context=(.*), type=(\\w+), id=(\\d+)><>(\\w+)"
      name: "jetty_servlet_$4"
      labels:
        id: "$3"
        type: "$2"
        context: "$1"
    - pattern: "org.eclipse.jetty.servlet<context=(.*), type=(\\w+), name=(\\w+), id=(\\d+)><>(\\w+)"
      name: "jetty_servlet_$5"
      labels:
        id: "$4"
        type: "$2"
        name: "$3"
        context: "$1"
    - pattern: "org.eclipse.jetty.util.thread<type=(\\w+), id=(\\d+)><>(\\w+)"
      name: "jetty_util_thread_$3"
      labels:
        id: "$2"
        type: "$1"
    - pattern: "org.eclipse.jetty.util.thread.strategy<context=(.*), type=(\\w+), id=(\\d+)><>(\\w+)"
      name: "jetty_util_thread_strategy_$4"
      labels:
        id: "$3"
        type: "$2"
        context: "$1"
    - pattern: "org.eclipse.jetty.webapp<context=(.*), type=(\\w+), id=(\\d+)><>(\\w+)"
      name: "jetty_webapp_$4"
      labels:
        id: "$3"
        type: "$2"
        context: "$1"
    - pattern: "org.eclipse.jetty.websocket.common<context=(.*), type=(\\w+), id=(\\d+)><>(\\w+)"
      name: "jetty_websocket_jakarta_common_$4"
      labels:
        id: "$3"
        type: "$2"
        context: "$1"
    - pattern: "org.eclipse.jetty.websocket.jakarta.common<context=(.*), type=(\\w+), id=(\\d+)><>(\\w+)"
      name: "jetty_websocket_jakarta_common_$4"
      labels:
        id: "$3"
        type: "$2"
        context: "$1"
    - pattern: "org.eclipse.jetty.(.*)"
      name: jetty_metric_$1
